id: 623de4b1-387b-4bdd-8d8e-aacbd0b69f9a
version: 2
name: '[CSIRT] - Cuckoo Malware Analysis - Automated'
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 473afec8-4337-47a8-876a-9bef6ead7b3b
    type: start
    task:
      id: 473afec8-4337-47a8-876a-9bef6ead7b3b
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: bc54305a-298c-49be-83e9-f3537c3c8156
    type: regular
    task:
      id: bc54305a-298c-49be-83e9-f3537c3c8156
      version: -1
      name: CuckooDetonateFile
      description: Adds a file to the list of pending tasks. Returns the ID of the
        newly created task.
      script: CuckooDetonateFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      enforce_timeout: {}
      entryID:
        simple: ${File.EntryID}
      machine: {}
      memory: {}
      options: {}
      package: {}
      platform: {}
      tags: {}
      timeout: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: f563d52e-bc1b-4111-8f42-30974040035d
    type: regular
    task:
      id: f563d52e-bc1b-4111-8f42-30974040035d
      version: -1
      name: cuckoo-view-task
      description: Returns details on the task associated with the specified ID
      script: Cuckoo Sandbox|||cuckoo-view-task
      type: regular
      iscommand: true
      brand: Cuckoo Sandbox
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      id:
        simple: ${CuckooTaskID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: 81998c42-a81b-4da7-86df-a8f699f54078
    type: condition
    task:
      id: 81998c42-a81b-4da7-86df-a8f699f54078
      version: -1
      name: Is report ready?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Cuckoo.Task.Status
            iscontext: true
          right:
            value:
              simple: reported
    view: |-
      {
        "position": {
          "x": 450,
          "y": 560
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: e126d3fa-f0e8-4a9b-8528-cf989d121740
    type: regular
    task:
      id: e126d3fa-f0e8-4a9b-8528-cf989d121740
      version: -1
      name: Get task report
      script: '|||cuckoo-get-task-report'
      type: regular
      iscommand: true
      brand: ""
    scriptarguments:
      id:
        simple: ${Cuckoo.Task.ID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {
      "3_4_yes": 0.5
    },
    "paper": {
      "dimensions": {
        "height": 865,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
