id: 623de4b1-387b-4bdd-8d8e-aacbd0b69f9a
version: 7
name: '[CSIRT] - Cuckoo Malware Analysis - Automated'
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 473afec8-4337-47a8-876a-9bef6ead7b3b
    type: start
    task:
      id: 473afec8-4337-47a8-876a-9bef6ead7b3b
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: bc54305a-298c-49be-83e9-f3537c3c8156
    type: regular
    task:
      id: bc54305a-298c-49be-83e9-f3537c3c8156
      version: -1
      name: CuckooDetonateFile
      description: Adds a file to the list of pending tasks. Returns the ID of the
        newly created task.
      script: CuckooDetonateFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      enforce_timeout: {}
      entryID:
        simple: ${File.EntryID}
      machine: {}
      memory: {}
      options: {}
      package: {}
      platform: {}
      tags: {}
      timeout: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: f563d52e-bc1b-4111-8f42-30974040035d
    type: regular
    task:
      id: f563d52e-bc1b-4111-8f42-30974040035d
      version: -1
      name: cuckoo-view-task
      description: Returns details on the task associated with the specified ID
      script: Cuckoo Sandbox|||cuckoo-view-task
      type: regular
      iscommand: true
      brand: Cuckoo Sandbox
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      id:
        simple: ${CuckooTaskID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: 66d1d4d4-bc2b-4be9-8e09-eacacbdc8b94
    type: condition
    task:
      id: 66d1d4d4-bc2b-4be9-8e09-eacacbdc8b94
      version: -1
      name: Is report ready?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Cuckoo.Task.Status
            iscontext: true
          right:
            value:
              simple: reported
    view: |-
      {
        "position": {
          "x": 450,
          "y": 660
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: 800a5d32-2c2f-467a-8a19-ba7dcd2792da
    type: regular
    task:
      id: 800a5d32-2c2f-467a-8a19-ba7dcd2792da
      version: -1
      name: Get task report
      script: '|||cuckoo-get-task-report'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      id:
        simple: ${Cuckoo.Task.ID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 860
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 3473c269-9084-42c1-8024-a24a16182c63
    type: regular
    task:
      id: 3473c269-9084-42c1-8024-a24a16182c63
      version: -1
      name: Update score
      description: Prints text to war room (Markdown supported)
      script: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      value:
        simple: ${Cuckoo.Task.Score}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1020
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: 9d006bc7-a2bd-4bc8-8e4c-d195c3d6969e
    type: title
    task:
      id: 9d006bc7-a2bd-4bc8-8e4c-d195c3d6969e
      version: -1
      name: END
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: a83b1b2a-d089-4d82-821b-df334a223376
    type: playbook
    task:
      id: a83b1b2a-d089-4d82-821b-df334a223376
      version: -1
      name: GenericPolling
      description: |-
        Use as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continually running the command in Step #2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      playbookId: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      AdditionalPollingCommandArgNames: {}
      AdditionalPollingCommandArgValues: {}
      Ids:
        simple: ${Cuckoo.Task.ID}
      Interval:
        simple: ${inputs.interval}
      PollingCommandArgName:
        simple: id
      PollingCommandName:
        simple: cuckoo-view-task
      Timeout:
        simple: ${inputs.timeout}
      dt:
        simple: Cuckoo.Task(val.CompletedOn == null).ID
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 450,
          "y": 500
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {
      "3_4_yes": 0.5
    },
    "paper": {
      "dimensions": {
        "height": 1195,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
