id: ab2b80aa-ff01-4232-8281-b8d10822ca7c
version: 3
name: '[CSIR] - Cuckoo Malware Analysis - Automated'
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 3812ffad-4365-469a-83c2-2519913c6b22
    type: start
    task:
      id: 3812ffad-4365-469a-83c2-2519913c6b22
      version: -1
      name: ""
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 65,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs:
- key: File
  value:
    simple: ${incident.filepath}
  required: false
  description: ""
outputs: []
