id: 20068f59-6b25-421e-8013-6ed608f3ba49
version: 3
name: '[CSIRT] - Cuckoo Report check - Automated'
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: c80422fd-ce37-4538-8497-f32a35e37ec8
    type: start
    task:
      id: c80422fd-ce37-4538-8497-f32a35e37ec8
      version: -1
      name: ""
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 65,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs:
- key: Cuckoo Task
  value: {}
  required: false
  description: ""
outputs: []
