id: 623de4b1-387b-4bdd-8d8e-aacbd0b69f9a
version: 6
name: '[CSIRT] - Cuckoo Malware Analysis - Automated'
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 473afec8-4337-47a8-876a-9bef6ead7b3b
    type: start
    task:
      id: 473afec8-4337-47a8-876a-9bef6ead7b3b
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: bc54305a-298c-49be-83e9-f3537c3c8156
    type: regular
    task:
      id: bc54305a-298c-49be-83e9-f3537c3c8156
      version: -1
      name: CuckooDetonateFile
      description: Adds a file to the list of pending tasks. Returns the ID of the
        newly created task.
      script: CuckooDetonateFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      enforce_timeout: {}
      entryID:
        simple: ${File.EntryID}
      machine: {}
      memory: {}
      options: {}
      package: {}
      platform: {}
      tags: {}
      timeout: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: f563d52e-bc1b-4111-8f42-30974040035d
    type: regular
    task:
      id: f563d52e-bc1b-4111-8f42-30974040035d
      version: -1
      name: cuckoo-view-task
      description: Returns details on the task associated with the specified ID
      script: Cuckoo Sandbox|||cuckoo-view-task
      type: regular
      iscommand: true
      brand: Cuckoo Sandbox
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      id:
        simple: ${CuckooTaskID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: e40e0ba4-c897-412e-8fb3-3c2c2b354150
    type: condition
    task:
      id: e40e0ba4-c897-412e-8fb3-3c2c2b354150
      version: -1
      name: Is report ready?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Cuckoo.Task.Status
            iscontext: true
          right:
            value:
              simple: reported
    view: |-
      {
        "position": {
          "x": 450,
          "y": 650
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: e126d3fa-f0e8-4a9b-8528-cf989d121740
    type: regular
    task:
      id: e126d3fa-f0e8-4a9b-8528-cf989d121740
      version: -1
      name: Get task report
      script: '|||cuckoo-get-task-report'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      id:
        simple: ${Cuckoo.Task.ID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 860
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 52d233e4-48be-46d9-86ed-ce601b390341
    type: condition
    task:
      id: 52d233e4-48be-46d9-86ed-ce601b390341
      version: -1
      name: Update score
      description: "Gets a value and return it. This is to be used in playbook conditional
        tasks - get a value from incident field, label or context, and act accordingly.
        \nIf an array is returned. the first value will be the decision making value."
      script: checkValue
      type: condition
      iscommand: false
      brand: ""
    scriptarguments:
      value:
        simple: ${Cuckoo.Task.Score}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1010
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: 9d006bc7-a2bd-4bc8-8e4c-d195c3d6969e
    type: title
    task:
      id: 9d006bc7-a2bd-4bc8-8e4c-d195c3d6969e
      version: -1
      name: END
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: a2d15fde-3914-4cde-83de-bb46367b2918
    type: regular
    task:
      id: a2d15fde-3914-4cde-83de-bb46367b2918
      version: -1
      name: Wait for report to generate
      description: Sleep for X seconds
      script: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      seconds:
        simple: "480"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 490
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: 4f64ed55-4599-481c-8ed0-cc650e18ba8f
    type: playbook
    task:
      id: 4f64ed55-4599-481c-8ed0-cc650e18ba8f
      version: -1
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    scriptarguments:
      AdditionalPollingCommandArgNames: {}
      AdditionalPollingCommandArgValues: {}
      Ids:
        simple: ${Cuckoo.Task.ID}
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: ids
      PollingCommandName: {}
      Timeout:
        simple: "10"
      dt: {}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 960,
          "y": 600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {
      "3_4_yes": 0.5
    },
    "paper": {
      "dimensions": {
        "height": 1195,
        "width": 890,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
